# Generated by Django 5.1 on 2024-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsview',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
