# Generated by Django 5.1 on 2024-08-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_newsview_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsview',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
